### ISSUE TITLE
Java Random NextInt Invalid Overload

### ISSUE THREAD

**Issue by serch037** [j4ts/j4ts#13]
Currently my code has something like this:
```java
Random rand = new Random();
int value = rand.nextInt(100);
```

however, after compiling with JSweet and adding j4ts (which by the way I have to do manually) I get the following log: 

> throw new Error('invalid overload');
> Error: invalid overload
>     at Function.InternalPreconditions.checkCriticalArgument (/home/sergio/Documents/Programming/JS/JSweet/tmp/my-app/newApp.js:19019:27)
>     at /home/sergio/Documents/Programming/JS/JSweet/tmp/my-app/newApp.js:4124:65
>     at Random.nextInt (/home/sergio/Documents/Programming/JS/JSweet/tmp/my-app/newApp.js:4140:23)
>     at Function.App.main (/home/sergio/Documents/Programming/JS/JSweet/tmp/my-app/newApp.js:20954:27)
>     at Object.<anonymous> (/home/sergio/Documents/Programming/JS/JSweet/tmp/my-app/newApp.js:20960:5)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)

However, if I remove call `rand.nextInt()` without arguments, the code works correctly.

Furthermore, removing the line:
 `                        javaemul.internal.InternalPreconditions.checkCriticalArgument(n > 0);
`
in j4ts.js, makes the overloaded version work. 

My j4ts.js is the one from master.

**Comment by schaumb** [comment]
I created an issue for jsweet transpiler:
https://github.com/cincheo/jsweet/issues/446

This not a j4ts bug, but the compiler affects on this.

**Comment by schaumb** [comment]
I PR -ed a solution for this issue inside j4ts repo. If that is accepted, then there is no bug :)
