### ISSUE TITLE
j4ts 0.4.0 release depends on org.jsweet:jsweet-core:5-SNAPSHOT

### ISSUE THREAD

**Issue by StormeHawke** [j4ts/j4ts#15]
Related to https://github.com/cincheo/jsweet/issues/272

Tracking down dependencies that aren't showing up with only the release repo exposed to maven, I figured out this is where maven is attempting to pull down a version of jsweet-core that doesn't exist in the release repository (in addition to attempting to pull down es6-promise from the jsweet transpiler)

```
                <dependency>
			<groupId>org.jsweet</groupId>
			<artifactId>jsweet-core</artifactId>
			<version>5-SNAPSHOT</version>
		</dependency>
```

On a related note - I tried forking so I can manually build this locally and I can't find any reference to v0.4.0 anywhere in the git history.  Was 0.4.0 developed in a since-deleted branch that was never merged to master?

**Comment by renaudpawlak** [comment]
Ok. version 0.4.0 was a mistake. Sorry about this. I have created and deployed version 0.3.0, which should remove wrong dependencies to snapshots. It is for JSweet v1.x. If you are using JSweet v2.x, you should avoid using J4TS if possible anyway.

So, the best way for you is to use the following dep:

```xml
<dependency>
	<groupId>org.jsweet.candies</groupId>
	<artifactId>j4ts</artifactId>
	<version>0.3.0</version>
</dependency>
```

I hope it will fix your issues.
