### ISSUE TITLE
j4ts 0.3.0 throwing duplicate identifier errors on transpile

### ISSUE THREAD

**Issue by StormeHawke** [j4ts/j4ts#16]
After pulling down j4ts 0.3.0 following [this](https://github.com/j4ts/j4ts/issues/15) being closed, I have a whole series of errors like this (this is an abbreviated set):

> 2017-05-23 11:10:47.047 INFO  JSweetTranspiler:1132 - ../../.jsweet/candies/typings/src/typings/j4ts/0.3.0/bundle.d.ts(6710,11): error TS2300: Duplicate identifier 'Hashtable'.
> 2017-05-23 11:10:47.047 ERROR output:46 - duplicate identifier 'Hashtable' at ../../.jsweet/candies/typings/src/typings/j4ts/0.3.0/bundle.d.ts(6710)
> 2017-05-23 11:10:47.047 INFO  JSweetTranspiler:1132 - ../../.jsweet/candies/typings/src/typings/j4ts/0.3.0/bundle.d.ts(6716,15): error TS2300: Duplicate identifier 'Hashtable'.
> 2017-05-23 11:10:47.047 ERROR output:46 - duplicate identifier 'Hashtable' at ../../.jsweet/candies/typings/src/typings/j4ts/0.3.0/bundle.d.ts(6716)
> 2017-05-23 11:10:47.047 INFO  JSweetTranspiler:1132 - ../../.jsweet/candies/typings/src/typings/j4ts/0.3.0/bundle.d.ts(6745,11): error TS2300: Duplicate identifier 'LinkedHashMap'.
> 2017-05-23 11:10:47.047 ERROR output:46 - duplicate identifier 'LinkedHashMap' at ../../.jsweet/candies/typings/src/typings/j4ts/0.3.0/bundle.d.ts(6745)
> 2017-05-23 11:10:47.047 INFO  JSweetTranspiler:1132 - ../../.jsweet/candies/typings/src/typings/j4ts/0.3.0/bundle.d.ts(6764,15): error TS2300: Duplicate identifier 'LinkedHashMap'.
> 2017-05-23 11:10:47.047 ERROR output:46 - duplicate identifier 'LinkedHashMap' at ../../.jsweet/candies/typings/src/typings/j4ts/0.3.0/bundle.d.ts(6764)

**Comment by renaudpawlak** [comment]
Sorry. My fault again (there is a flaw in the deployment process I need to fix). Please delete the artefact from your repo and try again. (maybe also delete the .jsweet directory of your project if it does not work right away).

**Comment by renaudpawlak** [comment]
can't you just delete the artifact from your mirror?

**Comment by StormeHawke** [comment]
I'm not in control of it, but I can ask the guy who is

**Comment by StormeHawke** [comment]
usually bug fixes come with a minor version bump though for this reason

**Comment by renaudpawlak** [comment]
yes... you are right. I will do it.

**Comment by renaudpawlak** [comment]
done

**Comment by StormeHawke** [comment]
Awesome, thanks for doing that.  I was able to pull it down and get a successful build.

As for https://github.com/cincheo/jsweet/issues/272 - I'm doing a version override on the `es6-promise` lib to force it to resolve, but is there any chance of a minor version bump there as well to fix that dependency that should be test scoped?

```
            <plugin>
                <groupId>org.jsweet</groupId>
                <artifactId>jsweet-maven-plugin</artifactId>
                <version>${org.jsweet.plugin.version}</version>
                <configuration>
                    <!-- Not sure why intellij shows these as errors but this is correct according to JSweet's documentation and it builds correctly -->
                    <targetVersion>ES5</targetVersion>
                    <tsOnly>false</tsOnly>
                    <bundle>true</bundle>
                    <sourceMap>true</sourceMap>
                    <includes>
                        <include>**/wfm/api/**/*.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <id>generate-js</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>jsweet</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.jsweet.candies</groupId>
                        <artifactId>es6-promise</artifactId>
                        <version>0.0.0-1.1.0-20160525</version>
                    </dependency>
                </dependencies>
            </plugin>

```

**Comment by renaudpawlak** [comment]
I am working on it...

**Comment by StormeHawke** [comment]
Thanks! This can be closed now, I got it working.  I still have to override the transpiler version in the jsweet-maven-plugin but I'd rather that than the es6-promise lib
