### ISSUE TITLE
ArrayList(Collection) constructor does not work correctly for JSweet 2.0

### ISSUE THREAD

**Issue by alievrenkut** [j4ts/j4ts#18]
```java
public ArrayList(Collection<? extends E> c) {
	  array = (E[]) new Object[0];
    // Avoid calling overridable methods from constructors
    ArrayHelper.insertTo(array, 0, c.toArray());
  }
```
`ArrayHelper.insertInto(this.array, 0, c.toArray())` method call inside constructor executes method
`ArrayHelper.insertInto(Object, index, Object)`
      instead of 
`ArrayHelper.insertInto(Object,index,Object[])`
which creates an invalid array inside ArrayList.

I guess this is a common problem in JSweet 2.0 with method dispatching when method is overloaded.

**Comment by schaumb** [comment]
I pushed a solution for this.
