### ISSUE TITLE
java.util.stream

### ISSUE THREAD

**Issue by enricostara** [j4ts/j4ts#19]
Hi,

do you plan to extend the support also for java.util.stream? 

Here I see that last GWT should already support java8 stream:
http://www.gwtproject.org/release-notes.html#Release_Notes_2_8_1

Best
E.

**Comment by renaudpawlak** [comment]
It is planned that JSweet 2 will offer built-in basic support for streams at some point (note that it is easy to add that support yourself by [writing an adapter](https://github.com/cincheo/jsweet/blob/master/doc/jsweet-language-specifications.md#extending-the-transpiler)). As for support in J4TS, well the idea would be to adapt the GWT's runtime to compile it with JSweet (should be fine). Don't hesitate to drop a link to the GWT implementation when available.

**Comment by enricostara** [comment]
Indeed, I put the question in J4TS but the need is to have such mapping in JSweet - I put the question here thinking that this was the good place :)

Therefore I'm going to spend some time to see adapter implementation in jsweet.

Thanks for your prompt and kind support,
Best
E

**Comment by renaudpawlak** [comment]
Obviously, you should be interested in this PR: https://github.com/j4ts/j4ts/pull/23
I think it solves your problem when using JSweet with J4TS, so I am closing this issue (unless you need more support). Supporting streams without J4TS should be a JSweet issue now...
