### ISSUE TITLE
Can not compile J4TS using JSweet 2.0

### ISSUE THREAD

**Issue by alievrenkut** [j4ts/j4ts#21]
I tried to compile J4TS with new JSweet 2.0 but it gives errors like:
* jsweet.util.Globals remaned to jsweet.util.Lang 
* $set,$get methods on Global has been removed.

I fixed these but now it complains about missing members in java.lang.Class which does not look easy to fix.

When do you plan to port J4TS for JSweet 2.0?

**Comment by renaudpawlak** [comment]
Ok. I have updated for JSweet v2 and merged back the development branch into J4TS master... I even released v0.5.0 and updated the master to v0.6.0-SNAPSHOT. Should be up-to-date now.
Thanks!
