### ISSUE TITLE
AbstractList.hashCode generating "invalid override" error

### ISSUE THREAD

**Issue by glooms** [j4ts/j4ts#26]
Hi!

I found an bug in the hashCode method of AbstractList in j4ts.js. It does not call the java.util.Collections.hashCode method with a reference to the object instance. Resulting in an error instead of a hashvalue.

I wrote a temporary fix which overrides this method:
`            AbstractList.prototype.hashCode = function () {
                return (function (o) { if (o.hashCode) {
                    return o.hashCode();
                }
                else {
                    return o.toString();
                } })(java.util.Collections);
            };`

with this:

`java.util.AbstractList.prototype.hashCode = function () {       
    let _this = this; 
        return (function (o) { if (o.hashCode) {  
            return o.hashCode(_this); 
        } else {
            return o.toString(_this);
        }})(java.util.Collections);                                                                  
};                
`
Since I don't know how the j4ts.js bundle is generated I simply hope that this information is of some help for anyone who does know. Or for anyone who happened to stumble on the same bug and wants a temporary workaround.

**Comment by schaumb** [comment]
It can be closed, because transpiler is fixed. :)

Now generates:
java.util.Collections.hashCode(this)
