### ISSUE TITLE
J4TS 0.2.0 Jar Files Missing the complete list of java.awt 

### ISSUE THREAD

**Issue by nathanawmk** [j4ts/j4ts#27]
Hi j4ts experts, please help... J4TS 0.2.0 Jar Files Missing the complete list of java.awt. For example, it does not have import java.awt.Checkbox; import java.awt.Choice; import java.awt.Font;.

Is there a J4TS Jar file that contains support for the full list of AWT?

import java.applet.Applet;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Checkbox;
import java.awt.CheckboxGroup;
import java.awt.Choice;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Label;
import java.awt.TextArea;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

![j4ts](https://user-images.githubusercontent.com/14244560/36372772-00cfe536-15a1-11e8-97eb-8e9c93df333d.png)

**Comment by schaumb** [comment]
At 0.2.0 version there are no exist these files:
https://github.com/j4ts/j4ts/tree/64e3c6850d82694a0a75395293cc8f8e1c4c8f3b/src/main/java/java/awt

Check the latest release, and latest builds

http://repository.jsweet.org/artifactory/webapp/#/artifacts/browse/tree/General/libs-release/org/jsweet/j4ts/0.5.0/j4ts-0.5.0.jar

**Comment by schaumb** [comment]
Okay, so there was a split, java.awt and javax.swing classes was mitigated to https://github.com/j4ts/j4ts-awt-swing repo.

It was only one snapshot build on this, which results can be download here:
http://repository.jsweet.org/artifactory/webapp/#/artifacts/browse/tree/General/libs-snapshot-local/org/jsweet/candies/j4ts/j4ts-awt-swing/0.0.1-SNAPSHOT/j4ts-awt-swing-0.0.1-20161130.073908-3.jar

It contains more classes than j4ts 0.2.0 version.

**Comment by lgrignon** [comment]
Thanks for summing this up

**Comment by lgrignon** [comment]
@nathanawmk  No sorry there is no official list, the repos are the list :)
