### ISSUE TITLE
J4TS 0.2.0 Jar Files Missing the complete list of java.awt

### ISSUE THREAD

**Issue by nathanawmk** [j4ts/j4ts#28]
Hi j4ts experts, please help... J4TS 0.2.0 Jar Files Missing the complete list of java.awt. For example, it does not have import java.awt.Checkbox; import java.awt.Choice; import java.awt.Font;.

Is there a J4TS Jar file that contains support for the full list of AWT?

import java.applet.Applet;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Checkbox;
import java.awt.CheckboxGroup;
import java.awt.Choice;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Label;
import java.awt.TextArea;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

![j4ts](https://user-images.githubusercontent.com/14244560/36386308-4771b580-15d0-11e8-9c5a-e07d50b3134f.png)

**Comment by schaumb** [comment]
duplicate @renaudpawlak #27

**Comment by schaumb** [comment]
I commented the other duplicated ticketet, I close this

**Comment by lgrignon** [comment]
Thanks!
