### ISSUE TITLE
TS2300: Duplicate identifier

### ISSUE THREAD

**Issue by tinca** [j4ts/j4ts#43]
Hi,

The next stop in my quest to transpile JHeaps is as follows:
> [org.jsweet.transpiler.TypeScript2JavaScriptWithTscTranspiler] ../../.jsweet/candies/typings/META-INF/resources/typings/j4ts/0.5.0-SNAPSHOT/bundle.d.ts(414,9): error TS2300: Duplicate identifier 'LOCAL_VARIABLE'.

Running gradle in debug mode reveals the bellow command line for tsc.

> /Users/zkuti/.jsweet-node_modules/bin/tsc --target ES6 --moduleResolution classic --experimentalDecorators --emitDecoratorMetadata --sourceMap --rootDir /Users/zkuti/projects-new/jheaps/target/ts --outDir /Users/zkuti/projects-new/jheaps/target/js .tsc-rootfile.ts org/jheaps/AddressableHeap.ts org/jheaps/tree/ReflectedFibonacciHeap.ts 
> ....
> org/jheaps/monotone/IntegerRadixAddressableHeap.ts org/jheaps/monotone/IntegerRadixHeap.ts org/jheaps/monotone/package-info.ts org/jheaps/monotone/DoubleRadixHeap.ts org/jheaps/package-info.ts org/jheaps/DoubleEndedHeap.ts org/jheaps/Constants.ts ../../.jsweet/candies/typings/META-INF/resources/typings/j4ts/0.5.0-SNAPSHOT/.tsc-rootfile.d.ts ../../.jsweet/candies/typings/META-INF/resources/typings/j4ts/0.5.0-SNAPSHOT/bundle.d.ts ../../.jsweet/candies/typings/src/typings/j4ts/0.3.1/.tsc-rootfile.d.ts ../../.jsweet/candies/typings/src/typings/j4ts/0.3.1/bundle.d.ts

It seems another (lower) version of j4ts has infiltrated. 
The actual dependency section is:
```
dependencies {
   compile group: 'org.jsweet', name: 'jsweet-core', version:'6-SNAPSHOT'
   compile group: 'org.jsweet', name: 'jsweet-transpiler', version:'2.2.0-SNAPSHOT'
    compile ('org.jsweet:j4ts:0.5.0-SNAPSHOT') 
}
```
Removing 0.5.0-SNAPSHOT all version gone away, so it seems it comes with 0.5.0 and indeed it can be found in the jar.

Can we have a clean 0.5.0 (or better 0.6.0) version? 

Thanks.

**Comment by tinca** [comment]
[Ping]

**Comment by lgrignon** [comment]
Hello @tinca , I am sorry to answer this late but we have only a few time those days. We are working on a way of maintaining better the JSweet project since all maintainers only have a few time, but in the mean time, any help is welcome if you want to give a try, I will be glad to review any PR.

**Comment by lgrignon** [comment]
For your issue, in the mean time, please use the snapshot version.

**Comment by tinca** [comment]
The problem is with the current version available, e.g. 0.5.0.
Lacking skill and time to contribute, the only thing I could try was unpacking 0.5.0, throwing out references of 0.3.1 and repacking the stuff. This resolved the problem and took me to a lot of other errors, but that's a different story.
