### ISSUE TITLE
Copy constructor for ArrayList does not work

### ISSUE THREAD

**Issue by Icare67** [j4ts/j4ts#51]
In the following example , I expect `a2` to be a copy of `al`. But it creates an array of array.
```java
public static void test()
	{
	        ArrayList<String> al = new ArrayList<String>();
		al.add("foo");
		al.add("bar");
		ArrayList<String> a2 = new ArrayList<String>(al);
		assert al.size() == a2.size();
	}
```

**Comment by schaumb** [comment]
It is solved here https://github.com/j4ts/j4ts/issues/18

**Comment by Icare67** [comment]
I'm using J4ts via maven.
I have this in my pom.xml file:
	<dependency>
			<groupId>org.jsweet</groupId>
			<artifactId>j4ts</artifactId>
			<version>0.5.0</version>
		</dependency> 
How can I benefit from your fix ?

**Comment by schaumb** [comment]
This change is on master branch. 
Currently there are no official revision which contains the modification. 

Can we create a new release @renaudpawlak ?

**Comment by lgrignon** [comment]
Sure, I will do it.

**Comment by lgrignon** [comment]
I upgraded to latest JSweet version, resolved some transpilation issues, and will soon be able to publish a release version.

**Comment by lgrignon** [comment]
done :)
http://repository.jsweet.org/artifactory/webapp/#/artifacts/browse/tree/General/libs-release-local/org/jsweet/j4ts/0.6.0/j4ts-0.6.0.jar

Could you please test it @Icare67

**Comment by Icare67** [comment]
I have checked out the master branch. Thanks
