### ISSUE TITLE
Snapshot jars contain classes for JDK libraries

### ISSUE THREAD

**Issue by dsyer** [j4ts/j4ts#67]
The release jars are clean, but 2.1.0-SNAPSHOT jars contain duplicate JDK classes that break any app that includes them. Example:

```
$ jar -tvf ~/.m2/repository/org/jsweet/j4ts/2.0.0/j4ts-2.0.0.jar | grep StringBuffer
$ jar -tvf ~/.m2/repository/org/jsweet/j4ts/2.1.0-SNAPSHOT/j4ts-2.1.0-SNAPSHOT.jar | grep StringBuffer
  7587 Sat Apr 10 20:03:34 BST 2021 java/lang/StringBuffer.class
```

**Comment by dsyer** [comment]
I don't know how this ever worked, but it can be fixed with some configuration for the jar plugin. E.g:

```xml

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.2.2</version>
				<configuration>
				  <excludes>
					<exclude>Object.class</exclude>
					<exclude>java/**</exclude>
					<exclude>javaemul/**</exclude>
				</excludes>
				</configuration>
			  </plugin>
```

**Comment by lgrignon** [comment]
Hey, thanks for noticing. This is not a problem on this example project using the same version:

https://github.com/lgrignon/j4ts-example/blob/master/pom.xml (please see GitHub Actions)

Is it a problem on a mixed project: Java + JSweet ? I mean do you need to both run a Java program, and transpile source in the same project?

If you want to file a PR, I would be glad to merge it

**Comment by lgrignon** [comment]
Thanks for contributing. Please feel free to send any improvment you may have in mind, I will always review / merge as quickly as possible
